---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mwright-chart-repo
  namespace: default
spec:
  type: "oci"
  interval: 1m0s
  url: oci://registry-1.docker.io/mwrightpivotal
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfd
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: node-feature-discovery
      version: "0.2.1"
      sourceRef:
        kind: HelmRepository
        name: mwright-chart-repo
        namespace: default
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  install:
    remediation:
      retries: -1
  test:
    enable: false
  values:
    namespaceOverride: nfd
